In [144]:
from sklearn.decomposition import PCA
import numpy as np
import pandas as pd

In [145]:
data = pd.read_csv('train.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 114321 entries, 0 to 114320
Columns: 133 entries, ID to v131
dtypes: float64(108), int64(6), object(19)
memory usage: 116.9+ MB

In [146]:
data.describe()

,ID,target,v1,v2,v4,v5,v6,v7,v8,v9,...,v121,v122,v123,v124,v126,v127,v128,v129,v130,v131
count,114321.000000,114321.000000,6.448900e+04,6.452500e+04,6.452500e+04,6.569700e+04,6.448900e+04,6.448900e+04,6.570200e+04,6.447000e+04,...,6.448100e+04,6.447000e+04,63643.000000,6.570200e+04,6.448900e+04,6.448900e+04,6.569700e+04,114321.000000,6.447800e+04,6.442600e+04
mean,114228.928228,0.761199,1.630686e+00,7.464411e+00,4.145098e+00,8.742359e+00,2.436402e+00,2.483921e+00,1.496569e+00,9.031859e+00,...,2.737596e+00,6.822439e+00,3.549938,9.198120e-01,1.672658e+00,3.239542e+00,2.030373e+00,0.310144,1.925763e+00,1.739389e+00
std,65934.487362,0.426353,1.082813e+00,2.961676e+00,1.148263e+00,2.036018e+00,5.999653e-01,5.894485e-01,2.783003e+00,1.930262e+00,...,1.356294e+00,1.795978e+00,2.604704,2.099407e+00,5.031683e-01,1.625988e+00,1.074232e+00,0.693262,1.264497e+00,1.134702e+00
min,3.000000,0.000000,-9.996497e-07,-9.817614e-07,-6.475929e-07,-5.287068e-07,-9.055091e-07,-9.468765e-07,-7.783778e-07,-9.828757e-07,...,-9.820642e-07,-9.978497e-07,0.019139,-9.994953e-07,-9.564174e-07,-9.223798e-07,8.197812e-07,0.000000,-9.901257e-07,-9.999134e-07
25%,57280.000000,1.000000,9.135798e-01,5.316428e+00,3.487398e+00,7.605918e+00,2.065064e+00,2.101477e+00,8.658986e-02,7.853659e+00,...,1.786965e+00,5.647712e+00,1.963315,2.053777e-02,1.417600e+00,2.101900e+00,1.393830e+00,0.000000,1.106172e+00,1.012658e+00
50%,114189.000000,1.000000,1.469550e+00,7.023803e+00,4.205991e+00,8.670867e+00,2.412790e+00,2.452166e+00,3.860317e-01,9.059582e+00,...,2.436195e+00,6.749117e+00,2.739239,1.398639e-01,1.614802e+00,2.963620e+00,1.798436e+00,0.000000,1.560138e+00,1.589403e+00
75%,171206.000000,1.000000,2.136128e+00,9.465497e+00,4.833250e+00,9.771353e+00,2.775285e+00,2.834285e+00,1.625246e+00,1.023256e+01,...,3.379175e+00,7.911392e+00,4.075361,8.718333e-01,1.843886e+00,4.108146e+00,2.390158e+00,0.000000,2.332425e+00,2.261905e+00
max,228713.000000,1.000000,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,...,2.000000e+01,2.000000e+01,19.686069,2.000000e+01,1.563161e+01,2.000000e+01,2.000000e+01,11.000000,2.000000e+01,2.000000e+01

In [147]:
compData = data.dropna() # complicated way: [~pd.isnull(data).any(1)], data with no NaNs

In [148]:
keys = set(compData.keys())

keys.remove('ID')
keys.remove('target')

compData2 = compData[list(keys)]

In [149]:
compData2.select_dtypes(include=['object']).describe()

,v110,v112,v113,v66,v91,v107,v79,v74,v75,v71,v125,v47,v22,v24,v56,v52,v30,v31,v3
count,17756,17756,17756,17756,17756,17756,17756,17756,17756,17756,17756,17756,17756,17756,17756,17756,17756,17756,17756
unique,2,22,34,3,7,7,11,2,2,3,86,7,6998,5,62,12,7,3,2
top,A,F,G,A,A,E,C,B,D,F,BM,I,YGJ,E,DO,J,C,A,C
freq,16771,2610,5207,11554,4108,4108,9495,17655,12563,12563,1018,10861,351,6313,2777,1740,10523,17391,17755

In [150]:
# pandas can do categorical into integer - pd.get_dummies(variable), but it creates a new column for each category

from sklearn import preprocessing as prep

_frame = pd.DataFrame(compData2.select_dtypes(include=['object'])).apply(prep.LabelEncoder().fit_transform)

for col in compData2:
    try:
        compData2.loc[:,col] = _frame[col]
    except KeyError:
        pass

In [152]:
compData2.head()

,v18,v19,v12,v13,v10,v11,v16,v17,v14,v15,...,v108,v1,v2,v3,v4,v5,v6,v7,v8,v9
21,0.540674,0.247953,9.233140,3.507230,5.229758,16.275460,6.730770,2.980920,14.376724,1.730492,...,2.144040,1.289841,4.788645,1,4.283417,10.719571,3.107570,1.962151,0.080812,8.604652
63,0.924447,0.166746,6.489439,4.440315,0.787746,14.225232,4.000000,8.302883,11.185820,2.936507,...,3.319248,2.495783,9.306134,1,6.572474,10.292470,3.001686,2.664418,0.511063,10.235293
64,1.081349,0.259039,6.099140,4.215789,0.525164,15.110132,6.072875,3.219932,11.636387,2.124495,...,1.371743,2.567534,7.514002,1,3.363238,5.243808,2.032217,2.299877,1.621858,7.568438
68,0.827621,0.176297,6.233500,3.714959,1.050329,15.277561,6.111111,6.940872,12.148604,2.002209,...,3.426396,1.312574,9.353351,1,5.289176,10.368787,3.342530,2.782814,0.287117,8.544892
73,1.031875,0.213928,6.149554,4.526062,1.050329,16.240929,4.444444,7.310717,10.829276,1.026193,...,3.008589,1.095601,6.772009,1,5.431377,10.202250,1.844332,1.920473,7.403780,6.277372

In [181]:
cData2_sc = prep.scale(compData2)

In [187]:
from sklearn.decomposition import PCA

pca = PCA(n_components=0.95)

In [188]:
cDataTransformed = pca.fit_transform(cData2_sc)

In [189]:
cDataTransformed.shape

(17756, 48)

In [190]:
np.cumsum(pca.explained_variance_ratio_)

array([ 0.20695043,  0.32516766,  0.40618083,  0.44761082,  0.48811398,
        0.51882801,  0.54610083,  0.57167497,  0.59627849,  0.61602005,
        0.63427423,  0.65181591,  0.66823991,  0.68398092,  0.69898518,
        0.71349894,  0.72718476,  0.74033733,  0.75302406,  0.76517623,
        0.77690631,  0.78839216,  0.79827723,  0.80764425,  0.81694622,
        0.82512676,  0.83300665,  0.84074694,  0.84840466,  0.85599318,
        0.86351106,  0.87087466,  0.87774734,  0.88426735,  0.89049889,
        0.89654585,  0.90251961,  0.90828142,  0.91398058,  0.91912922,
        0.9237897 ,  0.92840968,  0.93284453,  0.93722712,  0.94142072,
        0.94526768,  0.94879574,  0.95228786])

In [186]:
pca.n_components_

130